# Generated by Django 3.2 on 2023-03-11 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shares',
            options={'verbose_name_plural': 'Shares'},
        ),
        migrations.AlterModelOptions(
            name='sharestotal',
            options={'verbose_name_plural': 'Shares Total'},
        ),
        migrations.AlterField(
            model_name='shares',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
