# Generated by Django 3.2 on 2024-01-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_auto_20230311_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shares',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Shares'},
        ),
    ]
