# Generated by Django 3.2 on 2023-02-24 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('credit-deposit', 'Deposit'), ('credit-eoy', 'Year End Balance')], default='credit-deposit', max_length=50, verbose_name='Reason for Credit')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
            ],
            options={
                'verbose_name_plural': 'Savings Credit',
            },
        ),
        migrations.CreateModel(
            name='YearEndBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
            ],
            options={
                'verbose_name': 'Year End Balance',
                'verbose_name_plural': 'Year End Balances',
            },
        ),
        migrations.CreateModel(
            name='SavingsTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interest', models.BigIntegerField(default=0)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
            ],
            options={
                'verbose_name_plural': 'Savings Total',
            },
        ),
        migrations.CreateModel(
            name='SavingsInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interest', models.BigIntegerField(default=0)),
                ('is_comp', models.BooleanField(default=True, verbose_name='Is Compounding?')),
                ('start_comp', models.BooleanField(default=False, verbose_name='Started Compounding?')),
                ('disabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
                ('savings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='savings.savingscredit')),
            ],
            options={
                'verbose_name': 'Savings Interest',
                'verbose_name_plural': 'Savings Interests',
            },
        ),
        migrations.CreateModel(
            name='SavingsDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('debit-withdrawal', 'Withdrawal')], default='debit-withdrawal', max_length=50, verbose_name='Reason for Debit')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
            ],
            options={
                'verbose_name_plural': 'Savings Debit',
            },
        ),
    ]
