# Generated by Django 3.2 on 2023-03-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingsinterest',
            options={'verbose_name_plural': 'Savings Interests'},
        ),
    ]
