# Generated by Django 3.2 on 2023-02-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingscredit',
            options={'verbose_name_plural': 'Savings Credit'},
        ),
        migrations.AlterModelOptions(
            name='savingsdebit',
            options={'verbose_name_plural': 'Savings Debit'},
        ),
        migrations.AlterModelOptions(
            name='savingsinterest',
            options={'verbose_name': 'Savings Interest', 'verbose_name_plural': 'Savings Interests'},
        ),
        migrations.AlterModelOptions(
            name='savingstotal',
            options={'verbose_name_plural': 'Savings Total'},
        ),
        migrations.AlterModelOptions(
            name='yearendbalance',
            options={'verbose_name': 'Year End Balance', 'verbose_name_plural': 'Year End Balances'},
        ),
    ]
