# Generated by Django 3.2 on 2023-02-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_auto_20230221_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingscredit',
            name='reason',
            field=models.CharField(choices=[('credit-deposit', 'Deposit'), ('credit-eoy', 'Year End Balance')], default='credit-deposit', max_length=50, verbose_name='Reason for Credit'),
        ),
        migrations.AlterField(
            model_name='savingsdebit',
            name='reason',
            field=models.CharField(choices=[('debit-withdrawal', 'Withdrawal')], default='debit-withdrawal', max_length=50, verbose_name='Reason for Debit'),
        ),
    ]
