# Generated by Django 3.2 on 2023-03-19 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('savings', '0002_alter_savingsinterest_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsinterest',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='savingsinterest',
            name='is_comp',
        ),
        migrations.RemoveField(
            model_name='savingsinterest',
            name='start_comp',
        ),
        migrations.RemoveField(
            model_name='savingsinterest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='savingsinterest',
            name='total_interest',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='savingsinterest',
            name='savings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.savingscredit'),
        ),
        migrations.CreateModel(
            name='SavingsInterestTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interest', models.BigIntegerField(default=0)),
                ('is_comp', models.BooleanField(default=True, verbose_name='Is Compounding?')),
                ('start_comp', models.BooleanField(default=False, verbose_name='Started Compounding?')),
                ('disabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
                ('savings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='savings.savingscredit')),
            ],
            options={
                'verbose_name_plural': 'Savings Interests Total',
            },
        ),
    ]
