# Generated by Django 3.2 on 2025-01-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_member_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('name', 'account_number')},
        ),
    ]
