# Generated by Django 3.2 on 2023-02-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lir', models.FloatField(verbose_name='Loan Interest Rate')),
                ('sir', models.FloatField(default=4, verbose_name='Savings Interest Rate')),
                ('lsr', models.FloatField(default=10, verbose_name='Loan Savings Rate')),
                ('ld', models.IntegerField(default=6, verbose_name='Loan Duration')),
                ('psisd', models.IntegerField(default=3, verbose_name='Pre-Savings Interest Start Duration')),
                ('aad', models.IntegerField(default=6, verbose_name='Account Activity Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Account Types',
            },
        ),
        migrations.CreateModel(
            name='BusinessYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.IntegerField(default=1, verbose_name='Starting Day of Business Year')),
                ('start_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=4, verbose_name='Starting Month of Business Year')),
                ('end_day', models.IntegerField(default=31, verbose_name='Ending Day of Business Year')),
                ('end_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=3, verbose_name='Ending Month of Business Year')),
            ],
            options={
                'verbose_name_plural': 'Business Year',
            },
        ),
    ]
