# Generated by Django 3.2 on 2023-02-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountchoice',
            name='lir',
            field=models.FloatField(verbose_name='Loan Interest Rate'),
        ),
        migrations.AlterField(
            model_name='accountchoice',
            name='lsr',
            field=models.FloatField(default=10, verbose_name='Loan Savings Rate'),
        ),
        migrations.AlterField(
            model_name='accountchoice',
            name='sir',
            field=models.FloatField(default=4, verbose_name='Savings Interest Rate'),
        ),
    ]
