# Generated by Django 3.2 on 2023-02-08 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('outstanding_amount', models.BigIntegerField(default=0)),
                ('duration', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('status', models.CharField(choices=[('disbursed', 'Disbursed'), ('terminated', 'Terminated')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('terminated_at', models.DateTimeField()),
                ('guarantor_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantor_1', to='accounts.member')),
                ('guarantor_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantor_2', to='accounts.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanrequest')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
            ],
        ),
    ]
