# Generated by Django 3.2 on 2023-02-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loanrequest_terminated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('disbursed', 'Disbursed'), ('terminated', 'Terminated')], default='disbursed', max_length=50),
        ),
    ]
